#!/usr/bin/env bash
set -xe

pushd $(dirname $0)
mkdir -p ../maven

#./gradlew clean
./gradlew -PndkPath=/opt/android-sdk/ndk/28.0.12433566-beta1 build
rsync -a --progress --delete build/www/ ../maven/docs/

popd
