services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - worker:/worker
      - sdk:/opt/android-sdk
      - ./build/www:/worker/build/www

volumes:
  worker:
  sdk: